#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DTUProjectApp.Resource", IsApplication=true)]

namespace DTUProjectApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060011
			public const int createButtonConfirm = 2131099665;
			
			// aapt resource value: 0x7f060007
			public const int createProfileButton = 2131099655;
			
			// aapt resource value: 0x7f060010
			public const int emaileCreateEdit = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int loadingBarMain = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int mainTitleText = 2131099648;
			
			// aapt resource value: 0x7f060013
			public const int menu_LogOut = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int menu_edit = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int passwordEditCreate = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int passwordText = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int passwordTextEdit = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int signInAsGuestButton = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int signInButton = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int textView1 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int textView2 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int textView3 = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int textView4 = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int toolbar = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int userNameMainText = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int userNameTextEdit = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int usernameEditCreate = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int MainContent = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int NewProfileLayout = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int toolbar = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int toolbaritems = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int MyTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
